export const mockProducts = [
  {
    id: 1,
    name: "Plato Ducha Svelte",
    price: 39.11,
    photo: "/img/1.jpg",
    type: "dish",
  },
  {
    id: 2,
    name: "Plato Ducha Tropical",
    price: 257.92,
    photo: "/img/2.jpg",
    type: "dish",
  },
  {
    id: 3,
    name: "Plato Ducha Cabernet",
    price: 100,
    photo: "/img/3.jpg",
    type: "dish",
  },
  {
    id: 4,
    name: "Plato Ducha - Nappa",
    price: 250.9,
    photo: "/img/4.jpg",
    type: "dish",
  },
  {
    id: 5,
    name: "Plato Ducha Cup Dispenser",
    price: 175.85,
    photo: "/img/5.jpg",
    type: "dish",
  },
  {
    id: 6,
    name: "Plato Ducha - Malt",
    price: 82.61,
    photo: "/img/6.jpg",
    type: "dish",
  },
  {
    id: 7,
    name: "Espejo 8 Oz",
    price: 201.1,
    photo: "/img/7.jpg",
    type: "mirror",
  },
  {
    id: 8,
    name: "Espejo Raspberry",
    price: 134.99,
    photo: "/img/8.jpg",
    type: "mirror",
  },
  {
    id: 9,
    name: "Espejo Frenched",
    price: 199.16,
    photo: "/img/9.jpg",
    type: "mirror",
  },
  {
    id: 10,
    name: "Espejo Poppyseed",
    price: "123.82",
    photo: "/img/10.jpg",
    type: "mirror",
  },
];
